// Avtomatik yaratilgan (admin paneldagi o'zbekcha matn -> ruscha). Yangi matn qo'shilsa shu yerga qo'shing.
// `{}` — o'zgaruvchan qism (raqam, nom): u tarjimada ham shu tartibda turadi.
export const ADMIN_RU: Record<string, string> = {
  "Arizalar va xabarlar": "Заявки и сообщения",
  "Orkestr": "Оркестр",
  "Xor": "Хор",
  "Ansambl": "Ансамбль",
  "Kimdan": "От кого",
  "Til": "Язык",
  "Mavzu": "Тема",
  "Xabar": "Сообщение",
  "Jamoa nomi": "Название коллектива",
  "Turi": "Тип",
  "Viloyat": "Регион",
  "Shahar / tuman": "Город / район",
  "Rahbar / dirijyor": "Руководитель / дирижёр",
  "A'zolar soni": "Количество участников",
  "Bog'lanuvchi shaxs": "Контактное лицо",
  "Telefon": "Телефон",
  "{} yosh · {}": "{} лет · {}",
  "Yoshi": "Возраст",
  "Cholg‘u / yo‘nalish": "Инструмент / направление",
  "Video havolasi": "Ссылка на видео",
  "O‘zi haqida": "О себе",
  "Saytdagi formalar orqali tushgan murojaatlar. Har birining holatini belgilab boring — shunda nima ko‘rilgani aniq bo‘ladi.": "Обращения, поступившие через формы на сайте. Отмечайте статус каждого — так будет видно, что уже рассмотрено.",
  "Hammasi": "Все",
  "Aloqa xabarlari": "Сообщения обратной связи",
  "Jamoa arizalari": "Заявки коллективов",
  "Tanlov arizalari": "Заявки на конкурсы",
  "Iste’dod arizalari": "Заявки талантов",
  "Yangi": "Новая",
  "Ko‘rib chiqilmoqda": "На рассмотрении",
  "Javob berildi": "Ответ дан",
  "Rad etildi": "Отклонена",
  "Faqat yangilari": "Только новые",
  "Bu bo‘limda murojaat yo‘q.": "В этом разделе обращений нет.",
  "Katta ko‘rish uchun bosing": "Нажмите для увеличения",
  "Katta ochish": "Открыть крупно",
  "Javob yozish": "Написать ответ",
  "O‘chirish": "Удалить",
  "Ichki eslatma": "Внутренняя заметка",
  "Faqat xodimlar ko‘radi — saytda chiqmaydi": "Видна только сотрудникам — на сайте не отображается",
  "Faoliyat sahifasi": "Страница «Деятельность»",
  "Saytdagi": "Страница на сайте:",
  "sahifasi — menyudagi «Faoliyat» shu yerga olib boradi. Banner, kirish matni va pastdagi yo‘nalish kartochkalari shu yerdan boshqariladi.": "— пункт меню «Деятельность» ведёт сюда. Отсюда управляются баннер, вступительный текст и карточки направлений внизу страницы.",
  "Xatolik yuz berdi.": "Произошла ошибка.",
  "Foydalanuvchilar": "Пользователи",
  "Yopish": "Закрыть",
  "Yangi foydalanuvchi": "Новый пользователь",
  "Parol": "Пароль",
  "Kamida 8 ta belgi": "Не менее 8 символов",
  "Roli": "Роль",
  "Qo‘shish": "Добавить",
  "Parolni yozib oling — u shifrlanib saqlanadi va boshqa ko‘rsatilmaydi.": "Запишите пароль — он сохраняется в зашифрованном виде и больше не показывается.",
  "Admin": "Админ",
  "Tanlov admini": "Админ конкурсов",
  "· oxirgi kirish: {}": "· последний вход: {}",
  "Parolni almashtirish": "Сменить пароль",
  "Bloklash": "Заблокировать",
  "Faollashtirish": "Активировать",
  "O‘chirilsin": "Удалить?",
  "Bekor": "Отмена",
  "Yangi parol — kamida 8 ta belgi": "Новый пароль — не менее 8 символов",
  "Parolni saqlash": "Сохранить пароль",
  "Bo‘lim topilmadi": "Раздел не найден",
  "Bunday manzil yo‘q yoki yozuv o‘chirib yuborilgan. Chap menyudan kerakli bo‘limni tanlang.": "Такого адреса нет, либо запись удалена. Выберите нужный раздел в меню слева.",
  "Bosh sahifaga": "На главную",
  "Nusxalab bo‘lmadi — brauzer ruxsat bermadi.": "Не удалось скопировать — браузер не дал разрешения.",
  "Obunachilar": "Подписчики",
  "Jami": "Всего",
  "ta · faol obuna:": "· активных подписок:",
  "Nusxalandi": "Скопировано",
  "Faol emaillarni nusxalash": "Скопировать активные email",
  "Email bo‘yicha qidirish...": "Поиск по email...",
  "Hozircha obunachi yo‘q.": "Подписчиков пока нет.",
  "Hech narsa topilmadi.": "Ничего не найдено.",
  "Obunani to‘xtatish": "Отключить подписку",
  "Qayta faollashtirish": "Включить снова",
  "Bosh sahifa": "Главная",
  "Assalomu alaykum,": "Здравствуйте,",
  "Saytdagi barcha kontentni shu yerdan boshqarasiz. O‘zgarish saqlangan zahoti saytda ko‘rinadi.": "Отсюда вы управляете всем контентом сайта. Изменения появляются на сайте сразу после сохранения.",
  "Ariza qabuli": "Приём заявок",
  "Yangi murojaatlar": "Новые обращения",
  "Yangi, ko‘rilmagan murojaat yo‘q. Obunachilar soni:": "Новых непрочитанных обращений нет. Количество подписчиков:",
  "Kontent bo‘limlari": "Разделы контента",
  "{} ta qoralama": "{} черновиков",
  "hammasi saytda ko‘rinadi": "всё отображается на сайте",
  "Sayt sozlamalari": "Настройки сайта",
  "Kontakt ma’lumotlari, shior va ijtimoiy tarmoq havolalari. Bular saytning barcha sahifalarida — sarlavha, footer va «Aloqa» bo‘limida ishlatiladi.": "Контактные данные, слоган и ссылки на соцсети. Они используются на всех страницах сайта — в шапке, подвале и разделе «Контакты».",
  "Saqlandi": "Сохранено",
  "Saqlash": "Сохранить",
  "Pochta xabarnomasi": "Почтовые уведомления",
  "Yangi ariza kelganda yuqoridagi manzilga xat boradi. Sozlanganini shu yerda tekshirib ko‘ring — manzilni o‘zgartirgan bo‘lsangiz, avval Saqlang.": "При новой заявке письмо отправляется на указанный выше адрес. Проверьте здесь, что всё настроено — если вы меняли адрес, сначала нажмите «Сохранить».",
  "Yuborildi — pochtangizni tekshiring": "Отправлено — проверьте почту",
  "Sinov xati yuborish": "Отправить тестовое письмо",
  "Arizalar": "Заявки",
  "Excel’ga yuklab olish": "Скачать в Excel",
  "Ariza ochiq": "Заявки открыты",
  "Ariza yopiq": "Заявки закрыты",
  "Tez kunda": "Скоро",
  "Sana": "Дата",
  "Holat": "Статус",
  "Tanlov": "Конкурс",
  "Jamoa": "Коллектив",
  "Yo‘nalish": "Направление",
  "Qo‘shimcha ma’lumot": "Дополнительная информация",
  "Tanlov va festivallarga saytdan tushgan arizalar. Tanlovni tanlang — uning anketasi bo‘yicha javoblar ko‘rinadi.": "Заявки, поступившие с сайта на конкурсы и фестивали. Выберите конкурс — увидите ответы по его анкете.",
  "Barchasi ·": "Все ·",
  "Anketada {} ta savol": "В анкете вопросов: {}",
  "Anketa tuzilmagan — oddiy ariza shakli ishlatilmoqda": "Анкета не составлена — используется простая форма заявки",
  "Anketa va holatni tahrirlash": "Изменить анкету и статус",
  "Saytda ko‘rish": "Смотреть на сайте",
  "Eng so‘nggi": "Показаны последние",
  "ta ariza ko‘rsatilmoqda.": "заявок.",
  "Bo‘lim": "Раздел",
  "Topilmadi": "Не найдено",
  "Yangi {}": "Новая запись: {}",
  "{} — tahrirlash": "{} — редактирование",
  "➜ Yangi qadam": "➜ Новый шаг",
  "Ensemble name": "Название коллектива",
  "Region": "Регион",
  "Toshkent shahri": "г. Ташкент",
  "Toshkent viloyati": "Ташкентская обл.",
  "Andijon": "Андижан",
  "Buxoro": "Бухара",
  "Farg‘ona": "Фергана",
  "Jizzax": "Джизак",
  "Xorazm": "Хорезм",
  "Namangan": "Наманган",
  "Navoiy": "Навои",
  "Qashqadaryo": "Кашкадарья",
  "Qoraqalpog‘iston": "Каракалпакстан",
  "Samarqand": "Самарканд",
  "Sirdaryo": "Сырдарья",
  "Surxondaryo": "Сурхандарья",
  "Age": "Возраст",
  "Nominatsiya": "Номинация",
  "Category": "Категория",
  "Ijro videosi": "Видео выступления",
  "Ijro videosi havolasi": "Ссылка на видео выступления",
  "YouTube, Google Drive yoki boshqa ochiq havola": "YouTube, Google Drive или другая открытая ссылка",
  "Rozilik": "Согласие",
  "Shaxsiy ma’lumotlarimni qayta ishlashga roziman": "Я даю согласие на обработку моих персональных данных",
  "Repertuar": "Репертуар",
  "Ijro etiladigan asarlar": "Исполняемые произведения",
  "Ariza saytda": "Заявка на сайте",
  "to‘ldiriladi. 1-qadam — F.I.Sh. (familiya, ism, otasining ismi), 2-qadam — telefon va email: ular avtomatik so‘raladi. Savollarni qadamlarga bo‘lish uchun": "заполняется по шагам. Шаг 1 — Ф.И.О., шаг 2 — телефон и email: они запрашиваются автоматически. Чтобы разделить вопросы на шаги, добавьте",
  "“➜ Yangi qadam”": "«➜ Новый шаг»",
  "qo‘shing; birinchi qadamgacha bo‘lgan savollar 1-qadamga tushadi. Rozilik belgilari oxirgi — tasdiqlash qadamida chiqadi. Anketa bo‘sh qolsa, oddiy shakl ishlatiladi (jamoa nomi, yo‘nalish, izoh).": "; вопросы до первого шага попадут в шаг 1. Отметки согласия показываются на последнем шаге — подтверждении. Если анкета пуста, используется простая форма (название коллектива, направление, комментарий).",
  "Majburiy": "Обязательно",
  "Qadam sarlavhasi": "Заголовок шага",
  "Savol": "Вопрос",
  "— ariza sahifasida bundan keyingi savollar alohida qadamda chiqadi": "— следующие за ним вопросы на странице заявки появятся отдельным шагом",
  "Qabul qilinadigan fayl": "Принимаемый файл",
  "15 MB gacha. Fayllar yopiq saqlanadi — ularni faqat panelga kirgan xodimlar ochadi.": "До 15 МБ. Файлы хранятся закрыто — их могут открыть только сотрудники, вошедшие в панель.",
  "Variantlar": "Варианты",
  "— har biri alohida qatorda, tarjimalarda ham shu tartibda": "— каждый с новой строки, в переводах в том же порядке",
  "Qadam tavsifi": "Описание шага",
  "Izoh": "Пояснение",
  "(ixtiyoriy)": "(необязательно)",
  "Savol qo‘shish": "Добавить вопрос",
  "Hujjatlar bilan to‘liq anketa": "Полная анкета с документами",
  "Tayyor savollar:": "Готовые вопросы:",
  "Namuna": "Образец",
  "Faylda varaq topilmadi.": "В файле не найден лист.",
  "Fayl bo‘sh — birinchi satrda ustun sarlavhalari bo‘lishi kerak.": "Файл пуст — в первой строке должны быть заголовки столбцов.",
  "Bironta ham qator o‘qilmadi. Ustun sarlavhalari mos kelmayotgan bo‘lishi mumkin — namuna faylni yuklab olib tekshiring.": "Ни одной строки не прочитано. Возможно, заголовки столбцов не совпадают — скачайте образец файла и сверьтесь.",
  "Excel’dan yuklash": "Загрузить из Excel",
  "Namuna fayl": "Образец файла",
  "Birinchi satr — ustun sarlavhalari:": "Первая строка — заголовки столбцов:",
  ". Tilsiz ustun (masalan «": ". Столбец без языка (например «",
  "») o‘zbekcha deb olinadi.": "») считается узбекским.",
  "ta qator o‘qildi": "строк прочитано",
  "Bekor qilish": "Отменить",
  "Bu ustunlar faylda topilmadi va bo‘sh qoladi:": "Эти столбцы не найдены в файле и останутся пустыми:",
  "... va yana": "... и ещё",
  "Mavjudlariga qo‘shish": "Добавить к существующим",
  "Mavjud": "Заменить",
  "qatorni almashtirish": "существующих строк",
  "O‘zgarish shakl saqlangandan keyin bazaga yoziladi.": "Изменения записываются в базу после сохранения формы.",
  "ta qator": "строк",
  "{}-satr tashlab ketildi — {} bo‘sh": "Строка {} пропущена — {} пусто",
  "— tanlanmagan —": "— не выбрано —",
  "Bo‘sh — saytda o‘zbekcha matn ko‘rsatiladi.": "Пусто — на сайте показывается узбекский текст.",
  "O‘zbekchadan nusxalash": "Скопировать с узбекского",
  "Har bir band — alohida qatorda": "Каждый пункт — с новой строки",
  "Havoladan ID ajratildi:": "ID извлечён из ссылки:",
  ". Saytda pleyer bo‘lib ochiladi.": ". На сайте открывается как плеер.",
  "Bu yopiq kanal posti — uni saytga o‘rnatib bo‘lmaydi. Ochiq kanaldagi postning havolasini qo‘ying (https://t.me/kanal/123).": "Это пост из закрытого канала — его нельзя встроить на сайт. Вставьте ссылку на пост из открытого канала (https://t.me/kanal/123).",
  "Bu Instagramning «Ulashish» havolasi — ichida post kodi yo‘q. Saqlaganda sayt uni o‘zi ochib to‘g‘ri havolaga aylantirishga urinadi; bo‘lmasa, postni brauzerda ochib, manzil qatoridagi havolani (…/reel/KOD/) nusxalang.": "Это ссылка «Поделиться» из Instagram — в ней нет кода поста. При сохранении сайт попробует сам открыть её и превратить в правильную ссылку; если не получится, откройте пост в браузере и скопируйте ссылку из адресной строки (…/reel/КОД/).",
  "Havola tanilmadi. Saqlashda xato chiqadi — to‘liq havolani qo‘ying.": "Ссылка не распознана. При сохранении будет ошибка — вставьте полную ссылку.",
  "Instagram ({}/{})": "Instagram ({}/{})",
  "Yuklanmoqda... {}%": "Загрузка... {}%",
  "Yuklab bo‘lmadi.": "Не удалось загрузить.",
  "Rasmni olib tashlash": "Убрать изображение",
  "rasm yo‘q": "нет изображения",
  "Boshqa rasm yuklash": "Загрузить другое изображение",
  "Kompyuterdan rasm yuklash": "Загрузить изображение с компьютера",
  "JPG, PNG, WEBP — 15 MB gacha.": "JPG, PNG, WEBP — до 15 МБ.",
  "havolani yashirish": "скрыть ссылку",
  "yoki havola qo‘yish": "или вставить ссылку",
  "PDF, Word, Excel — 30 MB gacha": "PDF, Word, Excel — до 30 МБ",
  "Hujjat yuklash": "Загрузить документ",
  "MP4, WEBM, MOV — 50 MB gacha": "MP4, WEBM, MOV — до 50 МБ",
  "Video yuklash": "Загрузить видео",
  "Faylni olib tashlash": "Убрать файл",
  "Fayl yuklang yoki tashqi havola qo‘ying": "Загрузите файл или вставьте внешнюю ссылку",
  "Boshqa fayl yuklash": "Загрузить другой файл",
  "Hozircha bo‘sh": "Пока пусто",
  "Yuqoriga": "Вверх",
  "Pastga": "Вниз",
  "Qator qo‘shish": "Добавить строку",
  "Jami {} ta · saytda ko‘rinadi: {} ta": "Всего: {} · отображается на сайте: {}",
  "Ro‘yxatdan qidirish...": "Поиск по списку...",
  "Hozircha birorta {} qo‘shilmagan.": "Пока ничего не добавлено: {}.",
  "Qidiruv bo‘yicha hech narsa topilmadi.": "По запросу ничего не найдено.",
  "Birinchisini qo‘shish": "Добавить первую запись",
  "(nomsiz)": "(без названия)",
  "Saytda ko‘rsatish": "Показывать на сайте",
  "Qoralamaga olish": "Перенести в черновики",
  "Tahrirlash": "Редактировать",
  "Yangi {} qo‘shish": "Добавить: {}",
  "Qo‘shimcha maydonlar": "Дополнительные поля",
  "ta — ixtiyoriy)": "— необязательно)",
  "Ro‘yxatga qaytish": "Вернуться к списку",
  "Ishonchingiz komilmi?": "Вы уверены?",
  "Ha, o‘chirilsin": "Да, удалить",
  "Talent platformasi:": "Платформа талантов:",
  "saytda ko‘rinmoqda": "отображается на сайте",
  "saytda yopiq": "закрыта на сайте",
  "Sahifa saytda va menyuda ko‘rinib turibdi — yangi arizalar qabul qilinmoqda.": "Страница видна на сайте и в меню — новые заявки принимаются.",
  "Sahifa saytda ham, menyuda ham ko‘rinmayapti — yangi ariza qabul qilinmayapti.": "Страница не видна ни на сайте, ни в меню — новые заявки не принимаются.",
  "Kelib bo‘lgan arizalar «Arizalar va xabarlar» da turaveradi.": "Уже поступившие заявки остаются в разделе «Заявки и сообщения».",
  "Vaqtincha yopish": "Временно закрыть",
  "Qayta ochish": "Открыть снова",
  "Menyuni ochish": "Открыть меню",
  "Orkestr va Xor": "Оркестр и Хор",
  "Tanlov paneli": "Панель конкурсов",
  "Boshqaruv paneli": "Панель управления",
  "Menyuni yopish": "Закрыть меню",
  "Saytni ochish": "Открыть сайт",
  "Chiqish": "Выйти",
  "Kontent": "Контент",
  "Jamoalar": "Коллективы",
  "Loyihalar": "Проекты",
  "Afisha": "Афиша",
  "Yangiliklar": "Новости",
  "Videolar": "Видео",
  "Foto galereya": "Фотогалерея",
  "Tanlov va festivallar": "Конкурсы и фестивали",
  "Birlashma": "Объединение",
  "Rahbariyat": "Руководство",
  "Hujjatlar": "Документы",
  "Tashkiliy vazifalar": "Организационные задачи",
  "Sahifalar": "Страницы",
  "Xalqaro sahifalar": "Международные страницы",
  "Ekspertlar": "Эксперты",
  "Strategiya slaydlari": "Слайды стратегии",
  "Raqamlar (KPI)": "Цифры (KPI)",
  "Hamkorlar": "Партнёры",
  "Murojaatlar": "Обращения",
  "Sozlamalar": "Настройки",
  "Sahifa matnlari": "Тексты страниц",
  "Administrator": "Администратор",
  "hamma narsani boshqaradi": "управляет всем",
  "Muharrir": "Редактор",
  "kontentni tahrirlaydi": "редактирует контент",
  "faqat tanlov, festival va ularning arizalari": "только конкурсы, фестивали и их заявки",
  "Fayl juda katta — Storage qabul qilmadi (chegara 50 MB).": "Файл слишком большой — хранилище не приняло (лимит 50 МБ).",
  "Yuklab bo‘lmadi ({}). Qaytadan urinib ko‘ring.": "Не удалось загрузить ({}). Попробуйте ещё раз.",
  "Internet uzildi. Aloqani tekshirib, qaytadan urinib ko‘ring.": "Нет соединения с интернетом. Проверьте связь и попробуйте ещё раз.",
  "Yuklash to‘xtatildi.": "Загрузка остановлена.",
  "Fayl bo‘sh ko‘rinadi. Boshqa faylni tanlang.": "Файл выглядит пустым. Выберите другой файл.",
  "Sessiya tugagan. Sahifani yangilab, qaytadan kiring.": "Сессия истекла. Обновите страницу и войдите заново.",
  "Yuklashni boshlab bo‘lmadi. Qaytadan urinib ko‘ring.": "Не удалось начать загрузку. Попробуйте ещё раз.",
  "Email va parolni kiriting.": "Введите email и пароль.",
  "Email yoki parol noto‘g‘ri.": "Неверный email или пароль.",
  "Bu hisob boshqa foydalanuvchiga bog‘langan. Administratorga murojaat qiling.": "Эта учётная запись привязана к другому пользователю. Обратитесь к администратору.",
  "Kirish": "Войти",
  "Kirish — Boshqaruv paneli": "Вход — Панель управления",
  "Davom etish uchun tizimga kiring": "Войдите в систему, чтобы продолжить",
  "Parolni unutdingizmi? Tizim administratoriga murojaat qiling.": "Забыли пароль? Обратитесь к администратору системы.",
  "%s — Boshqaruv paneli": "%s — Панель управления",
  "Noma'lum model: {}": "Неизвестная модель: {}",
  "\"{}\" — o‘zbekcha matn to‘ldirilishi shart.": "«{}» — узбекский текст обязателен.",
  "\"{}\" — kamida bitta qator kerak.": "«{}» — нужна хотя бы одна строка.",
  "\"{}\" to‘ldirilishi shart.": "«{}» — обязательно для заполнения.",
  "\"{}\" — Instagram havolasi tanilmadi. Postni brauzerda ochib, manzil qatoridagi havolani nusxalang (masalan https://www.instagram.com/reel/ABC123/).": "«{}» — ссылка Instagram не распознана. Откройте пост в браузере и скопируйте ссылку из адресной строки (например https://www.instagram.com/reel/ABC123/).",
  "\"{}\" — Instagram havolasi tanilmadi. Postni brauzerda ochib, manzil": "«{}» — ссылка Instagram не распознана. Откройте пост в браузере и скопируйте ссылку из адресной",
  "\"{}\" — yopiq kanal postini saytga o‘rnatib bo‘lmaydi. Ochiq kanaldagi postning havolasini qo‘ying (https://t.me/kanal/123).": "«{}» — пост из закрытого канала нельзя встроить на сайт. Вставьте ссылку на пост из открытого канала (https://t.me/kanal/123).",
  "\"{}\" — yopiq kanal postini saytga o‘rnatib bo‘lmaydi.": "«{}» — пост из закрытого канала нельзя встроить на сайт.",
  "\"{}\" — havola tanilmadi. YouTube (https://youtu.be/…), Instagram post/reel (https://www.instagram.com/reel/…) yoki Telegram post (https://t.me/kanal/123) havolasini qo‘ying.": "«{}» — ссылка не распознана. Вставьте ссылку YouTube (https://youtu.be/…), пост/reel Instagram (https://www.instagram.com/reel/…) или пост Telegram (https://t.me/kanal/123).",
  "\"{}\" — YouTube ID noto‘g‘ri. To‘liq havolani qo‘ying (masalan https://www.youtube.com/watch?v=jNQXAC9IVRw) yoki 11 belgili ID ni kiriting.": "«{}» — неверный ID YouTube. Вставьте полную ссылку (например https://www.youtube.com/watch?v=jNQXAC9IVRw) или введите 11-значный ID.",
  "\"{}\" — YouTube ID noto‘g‘ri. To‘liq havolani qo‘ying": "«{}» — неверный ID YouTube. Вставьте полную ссылку",
  "\"{}\" juda uzun: {} belgi, ruxsat etilgani — {}.": "«{}» слишком длинное: {} симв., допустимо — {}.",
  "Bo‘lim topilmadi.": "Раздел не найден.",
  "Maydonlardan biri juda uzun bo‘lgani uchun saqlanmadi. Qisqartiring — masalan \"YouTube ID\" maydoniga to‘liq havola emas, faqat v= dan keyingi qism yoziladi.": "Не сохранено: одно из полей слишком длинное. Сократите — например, в поле «YouTube ID» вводится не полная ссылка, а только часть после v=.",
  "Xuddi shunday yozuv allaqachon bor. Nomni biroz o‘zgartirib, qaytadan saqlang.": "Такая запись уже существует. Немного измените название и сохраните снова.",
  "Saqlashda xatolik: {}": "Ошибка сохранения: {}",
  "Yozuv topilmadi.": "Запись не найдена.",
  "Ruxsat yo‘q. Qaytadan kiring.": "Нет доступа. Войдите заново.",
  "Bu amal faqat administrator uchun.": "Это действие доступно только администратору.",
  "Bu email allaqachon ro‘yxatdan o‘tgan.": "Этот email уже зарегистрирован.",
  "Email noto‘g‘ri.": "Неверный email.",
  "Ism to‘ldirilishi shart.": "Имя обязательно для заполнения.",
  "Parol kamida {} ta belgidan iborat bo‘lsin.": "Пароль должен содержать не менее {} символов.",
  "Foydalanuvchi topilmadi.": "Пользователь не найден.",
  "Supabase Auth’da bu hisob topilmadi.": "Эта учётная запись не найдена в Supabase Auth.",
  "O‘z hisobingizni bloklay olmaysiz.": "Вы не можете заблокировать свою учётную запись.",
  "O‘z rolingizni o‘zgartira olmaysiz.": "Вы не можете изменить свою роль.",
  "O‘z hisobingizni o‘chira olmaysiz.": "Вы не можете удалить свою учётную запись.",
  "Kamida bitta faol administrator qolishi kerak.": "Должен остаться хотя бы один активный администратор.",
  "Bu bo‘lim sizga ochiq emas.": "Этот раздел вам недоступен.",
  "Noma'lum murojaat turi: {}": "Неизвестный тип обращения: {}",
  "Obunachi topilmadi.": "Подписчик не найден.",
  "SMTP_USER yoki SMTP_PASS qo‘yilmagan. Ularni Vercel loyihasining \"Settings → Environment Variables\" bo‘limiga qo‘shing (SMTP_PASS — Google hisobidagi 16 belgili \"App password\") va saytni qayta joylang.": "Не заданы SMTP_USER или SMTP_PASS. Добавьте их в раздел «Settings → Environment Variables» проекта Vercel (SMTP_PASS — 16-значный «App password» аккаунта Google) и заново разверните сайт.",
  "✅ Sinov xati": "✅ Тестовое письмо",
  "Pochta xabarnomasi to‘g‘ri sozlangan": "Почтовые уведомления настроены правильно",
  "Qabul qiluvchi": "Получатель",
  "Tekshirdi": "Проверил",
  "Pochta serveri xatni qabul qilmadi. Eng ko‘p uchraydigan sabablar: \"App password\" noto‘g‘ri yoki eskirgan, Google hisobida ikki bosqichli tasdiqlash yoqilmagan, yoki qabul qiluvchi manzil xato yozilgan. Aniq sababi Vercel’dagi \"Logs\" bo‘limida ko‘rinadi.": "Почтовый сервер не принял письмо. Самые частые причины: «App password» неверный или устарел, в аккаунте Google не включена двухэтапная проверка, либо адрес получателя указан с ошибкой. Точная причина видна в разделе «Logs» на Vercel.",
  "\"{}\" — {}-qatorda \"{}\" to‘ldirilmagan. Uni to‘ldiring yoki qatorni o‘chiring.": "«{}» — в строке {} не заполнено «{}». Заполните его или удалите строку.",
  "\"{}\" — {}-qatorda \"{}\" to‘ldirilmagan.": "«{}» — в строке {} не заполнено «{}».",
  "\"{}\" — {}-qatorda {}": "«{}» — в строке {}: {}",
  "\"{}\" tanilmadi. Postni brauzerda ochib, manzil qatoridagi havolani nusxalang (masalan https://www.instagram.com/reel/ABC123/).": "«{}» не распознано. Откройте пост в браузере и скопируйте ссылку из адресной строки (например https://www.instagram.com/reel/ABC123/).",
  "\"{}\" tanilmadi. Postni brauzerda ochib, manzil qatoridagi havolani": "«{}» не распознано. Откройте пост в браузере и скопируйте ссылку из адресной строки",
  "\"{}\" tanilmadi. YouTube, Instagram yoki Telegram havolasini qo‘ying.": "«{}» не распознано. Вставьте ссылку YouTube, Instagram или Telegram.",
  "Saytda ko‘rinsin": "Показывать на сайте",
  "Belgilanmagan bo‘lsa — qoralama, saytda chiqmaydi": "Если не отмечено — черновик, на сайте не отображается",
  "Tartib raqami": "Порядковый номер",
  "Kichik raqam yuqorida turadi": "Меньшее число — выше в списке",
  "Bosh sahifada ko‘rsatilsin": "Показывать на главной",
  "Rasm": "Изображение",
  "Farg'ona": "Фергана",
  "Qoraqalpog'iston": "Каракалпакстан",
  "{} · {} a'zo": "{} · участников: {}",
  "Bosh dirijyor / rahbar": "Главный дирижёр / руководитель",
  "Tashkil etilgan yil": "Год основания",
  "Qisqa tavsif": "Краткое описание",
  "Katalogdagi kartochkada chiqadi — 1 jumla, 100–160 belgi": "Отображается в карточке каталога — 1 предложение, 100–160 символов",
  "Tarixi": "История",
  "1–2 abzats": "1–2 абзаца",
  "Banner rasmi": "Изображение баннера",
  "Gorizontal, 1600×700": "Горизонтальное, 1600×700",
  "Logotip": "Логотип",
  "Kvadrat, 800×800": "Квадрат, 800×800",
  "Tarkib": "Состав",
  "Bittalab kiritish yoki Excel jadvalni butunlay yuklash — a'zolar soni ko'p bo'lsa ikkinchisi qulay": "Вводить по одному или загрузить Excel-таблицу целиком — при большом числе участников второй способ удобнее",
  "Lavozimi": "Должность",
  "Bastakor": "Композитор",
  "Asar nomi": "Название произведения",
  "Har bir qatorda ikkitadan BITTASINI to‘ldiring: YouTube havolasi yoki Instagram post/reel havolasi.": "В каждой строке заполните ОДНО из двух: ссылку YouTube или ссылку на пост/reel Instagram.",
  "YouTube ID": "YouTube ID",
  "To‘liq havolani ham qo‘yish mumkin — ID o‘zi ajratiladi": "Можно вставить и полную ссылку — ID будет извлечён автоматически",
  "Instagram havolasi": "Ссылка Instagram",
  "Post yoki reel havolasi — masalan https://www.instagram.com/reel/ABC123/": "Ссылка на пост или reel — например https://www.instagram.com/reel/ABC123/",
  "Video nomi": "Название видео",
  "Muqova rasmi": "Обложка",
  "Instagram videosi uchun. Bo‘sh bo‘lsa Instagram belgisi chiqadi. YouTube o‘z rasmini oladi": "Для видео из Instagram. Если пусто, показывается значок Instagram. YouTube берёт своё изображение",
  "Xalqaro": "Международный",
  "Respublika": "Республиканский",
  "Loyiha nomi": "Название проекта",
  "Ko'lami": "Масштаб",
  "Respublika miqyosida": "В масштабе республики",
  "Xalqaro darajada": "На международном уровне",
  "Holati": "Статус",
  "Rejalashtirilgan": "Запланирован",
  "Davom etmoqda": "Идёт",
  "Yakunlangan": "Завершён",
  "Muddati": "Сроки",
  "Masalan: 2026-yil, oktyabr": "Например: октябрь 2026 года",
  "O'tkaziladigan joy": "Место проведения",
  "To'liq tavsif": "Полное описание",
  "Gorizontal, 1600×900": "Горизонтальное, 1600×900",
  "Natijalar": "Результаты",
  "Masalan: Ijrochilar — 250+": "Например: Исполнители — 250+",
  "Nomi": "Название",
  "Qiymati": "Значение",
  "Galereya": "Галерея",
  "Hamkor tashkilotlar": "Организации-партнёры",
  "Loyiha sayti": "Сайт проекта",
  "Loyihaning o‘z sayti yoki rasmiy sahifasi — masalan https://example.org. Ayniqsa xalqaro loyihalar uchun. To‘ldirilsa, loyihaning «Batafsil» sahifasida «Loyiha saytiga o‘tish» tugmasi chiqadi va yangi oynada o‘sha saytni ochadi. Bo‘sh qoldirilsa tugma ko‘rinmaydi.": "Собственный сайт или официальная страница проекта — например https://example.org. Особенно для международных проектов. Если заполнить, на странице «Подробнее» проекта появится кнопка «Перейти на сайт проекта», которая откроет этот сайт в новом окне. Если оставить пустым, кнопки не будет.",
  "Festival": "Фестиваль",
  "O'tkazilish sanasi": "Дата проведения",
  "Masalan: 2027-yil 15–21-mart": "Например: 15–21 марта 2027 года",
  "Nizom matni": "Текст положения",
  "Ishtirok kartasi: sarlavha": "Карточка участия: заголовок",
  "Ishtirok kartasi: qisqa izoh": "Карточка участия: краткое пояснение",
  "Ishtirok kartasi: ro‘yxat sarlavhasi": "Карточка участия: заголовок списка",
  "Ishtirok kartasi: tayyorlash kerak bo‘lgan narsalar": "Карточка участия: что подготовить заранее",
  "Nizom fayli": "Файл положения",
  "Arizalar tushadigan email": "Email для приёма заявок",
  "Mukofot jamg'armasi": "Призовой фонд",
  "Muddatlar jadvali": "График сроков",
  "Bosqich nomi": "Название этапа",
  "Hakamlar hay'ati": "Жюри",
  "Davlati": "Страна",
  "Surati": "Фото",
  "Ariza anketasi": "Анкета заявки",
  "Saytdagi \"Ariza topshirish\" oynasida shu savollar chiqadi. Tushgan arizalar — \"Tanlov arizalari\" bo‘limida.": "Эти вопросы появятся в окне «Подать заявку» на сайте. Поступившие заявки — в разделе «Заявки на конкурсы».",
  "Konsert": "Концерт",
  "Forum": "Форум",
  "Tadbir nomi": "Название мероприятия",
  "Turkumi": "Категория",
  "Sanasi": "Дата",
  "Boshlanish vaqti": "Время начала",
  "Zal / muassasa": "Зал / учреждение",
  "Shahar": "Город",
  "Chipta narxi": "Цена билета",
  "Masalan: 70 000 so‘mdan": "Например: от 70 000 сум",
  "Chipta havolasi": "Ссылка на билеты",
  "Ijrochi jamoa": "Исполнитель",
  "Poster": "Постер",
  "VERTIKAL rasm, 900×1200": "ВЕРТИКАЛЬНОЕ изображение, 900×1200",
  "Yangilik": "Новость",
  "Matbuot": "Пресса",
  "E'lon": "Объявление",
  "Sarlavha": "Заголовок",
  "Pastda post havolasi qo‘yilsa, sarlavha shart emas — saytda postning o‘zi ko‘rinadi. Yozib qo‘ysangiz, ro‘yxatda va sahifada shu sarlavha chiqadi.": "Если ниже вставлена ссылка на пост, заголовок не обязателен — на сайте виден сам пост. Если заполнить, в списке и на странице будет этот заголовок.",
  "Muallif / manba": "Автор / источник",
  "Qisqa mazmuni": "Краткое содержание",
  "Ro‘yxatdagi kartochkada chiqadi. Post havolasi qo‘yilsa — shart emas": "Отображается в карточке списка. Если вставлена ссылка на пост — не обязательно",
  "To'liq matn": "Полный текст",
  "Har bir abzats alohida qatorda yoziladi. Post havolasi qo‘yilsa shart emas — matnni postning o‘zi ko‘rsatadi": "Каждый абзац пишется с новой строки. Если вставлена ссылка на пост, не обязательно — текст показывает сам пост",
  "Gorizontal, 1200×800": "Горизонтальное, 1200×800",
  "Video yoki post havolasi (YouTube, Instagram, Telegram)": "Ссылка на видео или пост (YouTube, Instagram, Telegram)",
  "To‘liq havolani qo‘ying — masalan https://youtu.be/… , https://www.instagram.com/reel/… yoki https://t.me/kanal/123 . Yangilik sahifasida muqova ostida chiqadi: YouTube va Instagram pleyer bo‘lib o‘sha yerda ochiladi, Telegram posti esa matni va rasmi bilan to‘liq ko‘rinadi. Bo‘sh qoldirilsa hech narsa ko‘rinmaydi.": "Вставьте полную ссылку — например https://youtu.be/…, https://www.instagram.com/reel/… или https://t.me/kanal/123. Отображается на странице новости под обложкой: YouTube и Instagram открываются там же как плеер, а пост Telegram показывается целиком с текстом и изображением. Если оставить пустым, ничего не отобразится.",
  "Uchta usuldan BITTASINI to‘ldiring: YouTube ID, Instagram havolasi yoki video faylni yuklash. Instagram va yuklangan video uchun muqova rasmini ham qo‘ying.": "Заполните ОДИН из трёх способов: YouTube ID, ссылка Instagram или загрузка видеофайла. Для Instagram и загруженного видео добавьте также обложку.",
  "Yuklangan": "Загруженное",
  "To‘liq havolani qo‘ysangiz ham bo‘ladi — ID o‘zi ajratiladi": "Можно вставить и полную ссылку — ID будет извлечён автоматически",
  "Post yoki reel havolasi — masalan https://www.instagram.com/reel/ABC123/ . Ilovadagi «Ulashish» havolasi ham bo‘ladi: saqlaganda sayt uni haqiqiy havolaga aylantiradi. Muqova rasmi qo‘yilsa ro‘yxatda chiroyli ko‘rinadi.": "Ссылка на пост или reel — например https://www.instagram.com/reel/ABC123/. Подойдёт и ссылка «Поделиться» из приложения: при сохранении сайт превратит её в настоящую. Если добавить обложку, в списке будет красивее.",
  "Video fayl": "Видеофайл",
  "YouTube ham, Instagram ham bo‘lmasa — videoni shu yerdan yuklang": "Если нет ни YouTube, ни Instagram — загрузите видео отсюда",
  "Instagram va yuklangan video uchun. YouTube o‘z rasmini oladi": "Для Instagram и загруженного видео. YouTube берёт своё изображение",
  "Izohsiz surat": "Фото без подписи",
  "Vertikal": "Вертикальное",
  "Gorizontal": "Горизонтальное",
  "Kvadrat": "Квадратное",
  "Surat": "Фото",
  "Yo'nalishi": "Ориентация",
  "Vertikal, 600×800": "Вертикальное, 600×800",
  "Qisqacha ma'lumot": "Краткая информация",
  "Kartochkada chiqadi — 2–3 qator": "Отображается в карточке — 2–3 строки",
  "Batafsil ma'lumot": "Подробная информация",
  "Rahbar ustiga bosilganda ochiladigan oynada chiqadi: tarjimai hol, mehnat faoliyati, yutuqlar. Bo‘sh qator yangi abzatsni boshlaydi": "Отображается в окне, которое открывается при нажатии на руководителя: биография, трудовая деятельность, достижения. Пустая строка начинает новый абзац",
  "Unvon / daraja": "Звание / степень",
  "Qabul kunlari": "Дни приёма",
  "Davlat kodi": "Код страны",
  "2 harfli kod: DE, US, QA — bayroq shundan chiqadi": "Двухбуквенный код: DE, US, QA — флаг выбирается по нему",
  "Lavozimi / kasbi": "Должность / профессия",
  "Biografiyasi": "Биография",
  "Mutaxassislik yo'nalishlari": "Направления специализации",
  "Har bir yo‘nalish alohida qatorda": "Каждое направление — с новой строки",
  "Hamkorlik shakli": "Форма сотрудничества",
  "Saytdagi «Media → Matbuot uchun» bo‘limida chiqadi. Har bir yozuv bitta tadbirga tegishli: tadbir nomi, sanasi va press-reliz matni. Kartochka bosilganda to‘liq matn oynada ochiladi, fayl yuklangan bo‘lsa yuklab olish tugmasi ham chiqadi.": "Отображается в разделе «Медиа → Для прессы» на сайте. Каждая запись относится к одному мероприятию: название, дата и текст пресс-релиза. При нажатии на карточку полный текст открывается в окне, а если загружен файл, появляется и кнопка скачивания.",
  "Fayl bor": "Есть файл",
  "Ro‘yxatdagi kartochkada chiqadi — 1-2 jumla": "Отображается в карточке списка — 1–2 предложения",
  "Press-reliz matni": "Текст пресс-релиза",
  "Har bir abzats alohida qatorda yoziladi": "Каждый абзац пишется с новой строки",
  "Press-reliz fayli": "Файл пресс-релиза",
  "PDF yoki Word. Bo‘sh qoldirilsa yuklab olish tugmasi ko‘rinmaydi": "PDF или Word. Если оставить пустым, кнопка скачивания не отображается",
  "Hujjat nomi": "Название документа",
  "Hujjat fayli": "Файл документа",
  "Fayl haqida": "О файле",
  "Masalan: PDF · 480 KB": "Например: PDF · 480 КБ",
  "\"Birlashma haqida\" sahifasida raqamlangan kartochkalar bo‘lib chiqadi.": "На странице «Об объединении» отображаются пронумерованными карточками.",
  "Vazifa matni": "Текст задачи",
  "Bosh ekranda aylanib turadigan slaydlar.": "Слайды, сменяющиеся на главном экране.",
  "Yorliq": "Метка",
  "Masalan: I yo‘nalish": "Например: I направление",
  "Matn": "Текст",
  "Asosiy nuqtalar": "Основные пункты",
  "3 tadan yozilsa chiroyli chiqadi": "Красиво выглядит, если написать по 3",
  "Fon rasmi": "Фоновое изображение",
  "Gorizontal, 1920×1080": "Горизонтальное, 1920×1080",
  "ko'rsatkich": "показатель",
  "Bosh sahifada animatsiya bilan sanaladigan raqamlar.": "Цифры, которые считаются с анимацией на главной странице.",
  "Raqam": "Число",
  "Qo‘shimcha belgi": "Дополнительный знак",
  "Masalan: +": "Например: +",
  "Ikonka": "Иконка",
  "Kompas": "Компас",
  "Globus": "Глобус",
  "Bino": "Здание",
  "Kubok": "Кубок",
  "Radio": "Радио",
  "Ta’lim": "Образование",
  "Logotip matni": "Текст логотипа",
  "Rasm bo‘lmasa shu matn chiqadi": "Если нет изображения, показывается этот текст",
  "PNG, shaffof fon": "PNG, прозрачный фон",
  "Rasmiy sayti": "Официальный сайт",
  "Hamkorlik asosi": "Основа сотрудничества",
  "Faqat ichki foydalanish uchun — saytda chiqmaydi": "Только для внутреннего использования — на сайте не отображается",
  "Menyudagi «Xalqaro» ro‘yxatiga va /xalqaro sahifasiga avtomatik chiqadi. Yangi sahifa qo‘shish uchun kod o‘zgartirish shart emas.": "Автоматически появляется в списке «Международные» в меню и на странице /xalqaro. Для добавления новой страницы менять код не нужно.",
  "Sahifa nomi": "Название страницы",
  "Bannerda sarlavha ostida va /xalqaro ro‘yxatidagi kartochkada chiqadi": "Отображается в баннере под заголовком и в карточке списка /xalqaro",
  "Asosiy matn": "Основной текст",
  "Bo‘sh qator yangi abzatsni boshlaydi": "Пустая строка начинает новый абзац",
  "Foydali havolalar": "Полезные ссылки",
  "Sahifa oxirida ro‘yxat bo‘lib chiqadi — hamkor tashkilotlar, hujjatlar va h.k.": "Отображается списком в конце страницы — организации-партнёры, документы и т. д.",
  "Havola nomi": "Название ссылки",
  "Manzil": "Адрес",
  "Saytdagi tayyor yozuvlar: tugmalar, sarlavhalar va izohlar. Kulrang yozuv — matnning kodadagi kaliti, u qaysi sahifada chiqishini ko‘rsatadi. Maydon bo‘sh qoldirilsa, saytda standart matn ko‘rinadi. Kontent (yangiliklar, jamoalar, hujjatlar...), missiya matni va kontakt ma’lumotlari bu yerda emas — o‘z bo‘limlarida tahrirlanadi.": "Готовые надписи на сайте: кнопки, заголовки и пояснения. Серая надпись — ключ текста в коде, она показывает, на какой странице он отображается. Если оставить поле пустым, на сайте будет стандартный текст. Контент (новости, коллективы, документы...), текст миссии и контактные данные здесь не редактируются — они правятся в своих разделах.",
  "Uch tilda ham to‘ldiring — bo‘sh til uchun standart matn ishlatiladi": "Заполните на всех трёх языках — для пустого языка используется стандартный текст",
  "Tashkilot nomi": "Название организации",
  "Qisqa nomi": "Краткое название",
  "Logotip yonida va footerda chiqadi — masalan «Orkestr va Xor»": "Отображается рядом с логотипом и в подвале — например «Оркестр и Хор»",
  "Logotip ostidagi yozuv": "Надпись под логотипом",
  "Qisqa nom ostidagi mayda yozuv — masalan «Ijodiy birlashma»": "Мелкая надпись под кратким названием — например «Творческое объединение»",
  "Shior": "Слоган",
  "Missiya matni": "Текст миссии",
  "Missiya rasmi": "Изображение миссии",
  "\"Birlashma haqida\" sahifasida matn yonida chiqadi. Gorizontal, 900×700": "Отображается рядом с текстом на странице «Об объединении». Горизонтальное, 900×700",
  "«Birlashma haqida» sahifasi bannerdagi rasm": "Изображение в баннере страницы «Об объединении»",
  "Sahifaning eng tepasidagi to‘q ko‘k bannerda, sarlavhaning o‘ng yonida chiqadi. Gorizontal, 900×700. Bo‘sh qoldirilsa banner avvalgidek faqat matndan iborat bo‘ladi.": "Отображается в самом верху страницы в тёмно-синем баннере, справа от заголовка. Горизонтальное, 900×700. Если оставить пустым, баннер будет состоять только из текста, как раньше.",
  "Press-kit fayli": "Файл пресс-кита",
  "\"Media → Matbuot uchun\" bo‘limidagi yuklab olish tugmasi. Bo‘sh bo‘lsa tugma ko‘rinmaydi": "Кнопка скачивания в разделе «Медиа → Для прессы». Если пусто, кнопка не отображается",
  "Bosh sahifada «Raqamlarda birlashma» bloki ko‘rinsin": "Показывать на главной блок «Объединение в цифрах»",
  "Belgi olib tashlansa blok saytda umuman chiqmaydi. Ko‘rsatkichlarning o‘zi «Raqamlar (KPI)» bo‘limida kiritiladi — u yerda bironta ochiq ko‘rsatkich bo‘lmasa, belgi turgan bo‘lsa ham blok ko‘rinmaydi.": "Если снять отметку, блок вообще не появится на сайте. Сами показатели вводятся в разделе «Цифры (KPI)» — если там нет ни одного включённого показателя, блок не отображается даже при включённой отметке.",
  "Jamoa sahifasida «Tarkib» bloki ko‘rinsin": "Показывать на странице коллектива блок «Состав»",
  "Jamoaning a’zolari ro‘yxati. Belgi olib tashlansa blok saytda umuman chiqmaydi — ma’lumot hali yig‘ilmagan bo‘lsa shunday qoldiring. Belgi tursa ham, jamoaga bironta a’zo kiritilmagan bo‘lsa blok ko‘rinmaydi.": "Список участников коллектива. Если снять отметку, блок вообще не появится на сайте — оставьте так, если данные ещё не собраны. Даже при включённой отметке блок не отображается, если у коллектива нет ни одного участника.",
  "Jamoa sahifasida «Repertuar» bloki ko‘rinsin": "Показывать на странице коллектива блок «Репертуар»",
  "Jamoaning asarlar ro‘yxati. Belgi olib tashlansa blok saytda umuman chiqmaydi. Belgi tursa ham, repertuar kiritilmagan jamoada blok ko‘rinmaydi.": "Список произведений коллектива. Если снять отметку, блок вообще не появится на сайте. Даже при включённой отметке блок не отображается у коллектива без репертуара.",
  "Talent platformasi saytda ko‘rinsin": "Показывать платформу талантов на сайте",
  "Belgi olib tashlansa «Talent» sahifasi saytda umuman ko‘rinmaydi: menyudan, footerdan va bosh sahifadagi yo‘nalishlardan chiqib ketadi, manzili to‘g‘ridan-to‘g‘ri terilsa ham sahifa topilmadi deb javob beradi va ariza qabul qilinmaydi. Oldin kelgan arizalar joyida qoladi. Shu tugma admin panelning bosh sahifasida ham bor — bir bosishda yopib-ochiladi.": "Если снять отметку, страница «Таланты» вообще не отображается на сайте: пропадает из меню, подвала и направлений на главной; при прямом вводе адреса отвечает «страница не найдена», заявки не принимаются. Ранее поступившие заявки остаются на месте. Эта же кнопка есть на главной странице админ-панели — закрывается и открывается одним нажатием.",
  "Ish vaqti": "Время работы",
  "Sayt manzili": "Адрес сайта",
  "Xabarnoma pochtasi": "Почта для уведомлений",
  "Yangi ariza kelganda shu manzilga xat boradi. Bir nechta odamga yuborish uchun manzillarni vergul bilan ajrating. Bo‘sh qoldirilsa xat saytning o‘z pochtasiga (SMTP_USER) boradi.": "При новой заявке письмо отправляется на этот адрес. Чтобы отправлять нескольким людям, разделите адреса запятой. Если оставить пустым, письмо уходит на собственную почту сайта (SMTP_USER).",
  "Xarita — kenglik (lat)": "Карта — широта (lat)",
  "Masalan: 41.311081": "Например: 41.311081",
  "Xarita — uzunlik (lng)": "Карта — долгота (lng)",
  "Masalan: 69.279737": "Например: 69.279737",
  "Ijtimoiy tarmoqlar": "Социальные сети",
  "Tarmoq": "Сеть",
  "Havola": "Ссылка",
  "Sarlavha ostidagi jumla": "Фраза под заголовком",
  "Bannerda sarlavha ostida chiqadi — 1 jumla": "Отображается в баннере под заголовком — 1 предложение",
  "Kirish matni": "Вступительный текст",
  "Bo'sh qator yangi abzatsni boshlaydi": "Пустая строка начинает новый абзац",
  "Kirish matni yonidagi rasm": "Изображение рядом с вступительным текстом",
  "Gorizontal, 900×700. Bo'sh bo'lsa matn butun kenglikni egallaydi": "Горизонтальное, 900×700. Если пусто, текст занимает всю ширину",
  "Yo'nalish bloklari": "Блоки направлений",
  "Sahifa pastidagi kartochkalar. Havola — sayt ichidagi manzil, masalan /loyihalar": "Карточки внизу страницы. Ссылка — адрес внутри сайта, например /loyihalar",
  "Blok nomi": "Название блока",
  "Talent platformasi": "Платформа талантов",
  "Papka (loyiha)": "Папка (проект)",
  "Kubok (tanlov)": "Кубок (конкурс)",
  "Ta'lim (talent)": "Образование (таланты)",
  "Kalendar (afisha)": "Календарь (афиша)",
  "Globus (xalqaro)": "Глобус (международное)",
  "Noma’lum shakl.": "Неизвестная форма.",
  "Ishtirokchi": "Участник",
  "Faylni ochish": "Открыть файл",
  "O'zbekcha": "Узбекский",
  "Ruscha": "Русский",
  "Inglizcha": "Английский",
  "Qisqa matn": "Короткий текст",
  "Uzun matn": "Длинный текст",
  "Son": "Число",
  "Havola (video, fayl)": "Ссылка (видео, файл)",
  "Ro‘yxatdan tanlash": "Выбор из списка",
  "Bitta variant": "Один вариант",
  "Bir nechta variant": "Несколько вариантов",
  "Fayl yuklash (surat, hujjat)": "Загрузка файла (фото, документ)",
  "Rozilik belgisi": "Отметка согласия",
  "➜ Yangi qadam (sarlavha)": "➜ Новый шаг (заголовок)",
  "Faqat rasm (JPG, PNG, WEBP)": "Только изображение (JPG, PNG, WEBP)",
  "Faqat PDF": "Только PDF",
  "Rasm yoki hujjat (JPG, PNG, WEBP, PDF, Word)": "Изображение или документ (JPG, PNG, WEBP, PDF, Word)",
  "Anketa: {} matni (o‘zbekcha) yozilmagan.": "Анкета: текст {} (на узбекском) не заполнен.",
  "Anketa: \"{}\" savoliga kamida bitta variant yozing.": "Анкета: для вопроса «{}» укажите хотя бы один вариант.",
  "Ha": "Да",
  "iPhone’ning HEIC formatidagi rasmi — sayt uni ko‘rsata olmaydi. Telefonda \"Sozlamalar → Kamera → Formatlar → Eng mos\" ni tanlang yoki rasmni JPG ga o‘giring.": "Изображение iPhone в формате HEIC — сайт не может его показать. На телефоне выберите «Настройки → Камера → Форматы → Наиболее совместимые» или конвертируйте изображение в JPG.",
  ".{} formatidagi video brauzerda ochilmaydi. MP4 ga o‘girib yuklang.": "Видео в формате .{} не открывается в браузере. Конвертируйте в MP4 и загрузите.",
  "Bu turdagi fayl ({}) yuklanmaydi. Rasm — JPG, PNG, WEBP, AVIF, GIF, SVG; hujjat — PDF, Word, Excel; video — MP4, WEBM, MOV.": "Файлы этого типа ({}) не загружаются. Изображения — JPG, PNG, WEBP, AVIF, GIF, SVG; документы — PDF, Word, Excel; видео — MP4, WEBM, MOV.",
  "Bu turdagi fayl ({}) yuklanmaydi.": "Файлы этого типа ({}) не загружаются.",
  "Video {} MB — chegara {} MB. Videoni siqing yoki YouTube’ga joylab, \"YouTube ID\" maydoniga havolasini qo‘ying.": "Видео {} МБ — лимит {} МБ. Сожмите видео или разместите на YouTube и вставьте ссылку в поле «YouTube ID».",
  "Video {} MB — chegara {} MB. Videoni siqing yoki YouTube’ga": "Видео {} МБ — лимит {} МБ. Сожмите видео или разместите на YouTube",
  "Fayl": "Файл",
  "{} {} MB — chegara {} MB. Kichraytirib qayta yuklang.": "{} {} МБ — лимит {} МБ. Уменьшите и загрузите заново.",
  "Fayl yo‘li noto‘g‘ri.": "Неверный путь к файлу.",
  "Fayl topilmadi.": "Файл не найден."
};

/** Qo'lda qo'shilgan: bitta so'zli yoki bo'laklarga bo'linib chiqadigan matnlar */
export const ADMIN_RU_QOSHIMCHA: Record<string, string> = {
  'saqlanmoqda...': 'сохраняется...',
  saqlandi: 'сохранено',
  siz: 'вы',
  bloklangan: 'заблокирован',
  ta: 'шт.',
  'ta.': 'шт.',
  yangi: 'новых',
  'qadamma-qadam': 'по шагам',
  'Tanildi:': 'Распознано:',
  '-qator': '-я строка',
  'jNQXAC9IVRw yoki to‘liq havola': 'jNQXAC9IVRw или полная ссылка',
  'https://youtu.be/… , https://www.instagram.com/reel/… yoki https://t.me/kanal/123':
    'https://youtu.be/… , https://www.instagram.com/reel/… или https://t.me/kanal/123',
  'Boshqaruv paneli': 'Панель управления',
  '{} — Boshqaruv paneli': '{} — Панель управления',
  // «birlik» — bo'lim yozuvining nomi: "Yangi {} qo‘shish", "{} — tahrirlash" ichida chiqadi
  jamoa: 'коллектив',
  loyiha: 'проект',
  tanlov: 'конкурс',
  tadbir: 'мероприятие',
  yangilik: 'новость',
  video: 'видео',
  surat: 'фото',
  rahbar: 'руководитель',
  ekspert: 'эксперт',
  'press-reliz': 'пресс-релиз',
  hujjat: 'документ',
  vazifa: 'задача',
  slayd: 'слайд',
  "ko'rsatkich": 'показатель',
  hamkor: 'партнёр',
  sahifa: 'страница',
  matn: 'текст',
};
